# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  generate_weekly_reports:
    class: GenerateRoutineClubReportsJob
    args: [ "weekly" ]
    schedule: "at 6am every Monday"

  generate_monthly_reports:
    class: GenerateRoutineClubReportsJob
    args: [ "monthly" ]
    schedule: "0 7 1 * *"  # 매월 1일 오전 7시 (UTC)

  club_morning_push:
    class: ClubPushNotificationJob
    args: [ "morning_reminder" ]
    schedule: "0 0 * * *" # 매일 오전 9시 (KST = UTC 00:00)

  club_evening_push:
    class: ClubPushNotificationJob
    args: [ "evening_check" ]
    schedule: "0 13 * * *" # 매일 오후 10시 (KST = UTC 13:00)
