# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  generate_weekly_reports:
    class: GenerateRoutineClubReportsJob
    args: [ "weekly" ]
    schedule: "at 6am every Monday"

  generate_monthly_reports:
    class: GenerateRoutineClubReportsJob
    args: [ "monthly" ]
    schedule: "0 7 1 * *"  # 매월 1일 오전 7시 (UTC)

  club_push_checker:
    class: ClubPushNotificationJob
    schedule: "*/1 * * * *" # 1분마다 실행하여 HH:MM 스케줄 정시에 체크

  club_performance_check:
    class: ClubPerformanceCheckJob
    schedule: "at 00:01 every Monday"
